-- =====================================================
-- SupplyPrescript Database Tables
-- =====================================================

USE supply_prescript_db;

-- =====================================================
-- Table 1: Supply Chain Data
-- Stores cleaned operational supply-chain records
-- =====================================================

CREATE TABLE IF NOT EXISTS supply_chain_data (
    record_id BIGINT AUTO_INCREMENT PRIMARY KEY,

    warehouse_inventory_level DOUBLE,
    handling_equipment_availability DOUBLE,
    order_fulfillment_status DOUBLE,
    weather_condition_severity DOUBLE,
    shipping_costs DOUBLE,
    supplier_reliability_score DOUBLE,
    lead_time_days DOUBLE,
    historical_demand DOUBLE,
    cargo_condition_status DOUBLE,
    route_risk_level DOUBLE,
    customs_clearance_time DOUBLE,
    disruption_likelihood_score DOUBLE,
    delay_probability DOUBLE,

    risk_classification VARCHAR(50),

    delivery_time_deviation DOUBLE,

    product_id VARCHAR(100),
    supplier_id VARCHAR(100),
    supplier_country VARCHAR(100),

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- =====================================================
-- Table 2: Predictions
-- Stores risk predictions generated by ML model
-- =====================================================

CREATE TABLE IF NOT EXISTS predictions (
    prediction_id BIGINT AUTO_INCREMENT PRIMARY KEY,

    record_id BIGINT NOT NULL,

    predicted_risk_class VARCHAR(50),
    prediction_confidence DOUBLE,
    predicted_delay_probability DOUBLE,

    model_name VARCHAR(100),
    model_version VARCHAR(50),

    predicted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (record_id)
        REFERENCES supply_chain_data(record_id)
);

-- =====================================================
-- Table 3: Prescriptive Recommendations
-- Stores optimized mitigation actions
-- =====================================================

CREATE TABLE IF NOT EXISTS prescriptive_recommendations (
    recommendation_id BIGINT AUTO_INCREMENT PRIMARY KEY,

    record_id BIGINT NOT NULL,

    recommendation_rank INT,
    action VARCHAR(100),

    action_cost DOUBLE,
    risk_reduction DOUBLE,
    time_saved_days DOUBLE,
    capacity_required DOUBLE,
    operational_impact DOUBLE,
    optimization_score DOUBLE,

    budget_valid BOOLEAN,
    time_valid BOOLEAN,
    capacity_valid BOOLEAN,
    all_constraints_satisfied BOOLEAN,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (record_id)
        REFERENCES supply_chain_data(record_id)
);

-- =====================================================
-- Table 4: Decision Log
-- Stores the final action selected for each record
-- =====================================================

CREATE TABLE IF NOT EXISTS decision_log (
    decision_id BIGINT AUTO_INCREMENT PRIMARY KEY,

    record_id BIGINT NOT NULL,
    recommendation_id BIGINT,

    selected_action VARCHAR(100),

    expected_cost DOUBLE,
    expected_risk_reduction DOUBLE,
    expected_time_saved_days DOUBLE,

    decision_status VARCHAR(50) DEFAULT 'PENDING',

    selected_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (record_id)
        REFERENCES supply_chain_data(record_id),

    FOREIGN KEY (recommendation_id)
        REFERENCES prescriptive_recommendations(recommendation_id)
);

-- =====================================================
-- Table 5: Actual Outcomes
-- Stores actual results after implementing a decision
-- Used later for closed-loop feedback
-- =====================================================

CREATE TABLE IF NOT EXISTS actual_outcomes (
    outcome_id BIGINT AUTO_INCREMENT PRIMARY KEY,

    decision_id BIGINT NOT NULL,

    actual_cost DOUBLE,
    actual_delay_days DOUBLE,
    actual_risk_reduction DOUBLE,

    outcome_status VARCHAR(50),

    evaluated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (decision_id)
        REFERENCES decision_log(decision_id)
);